name: upgrader_example
description: Demonstrates how to use the upgrader package.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.1 <4.0.0'
  flutter: ">=3.0.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  device_info_plus: ^11.0.0
  go_router: ^7.1.1
  http: ^1.2.2
  path: ^1.9.0

  upgrader:
    path: ../
  version: ^3.0.2

dev_dependencies:
  flutter_driver:
    sdk: flutter

  flutter_lints:

  flutter_test:
    sdk: flutter

  test:

flutter:
  uses-material-design: true
