name: upgrader
description: Flutter package for prompting users to upgrade when there is a newer version of the app in the store.
version: 3.0.0-nullsafety.2
homepage: https://github.com/larryaasen/upgrader

environment:
  sdk: '>=2.12.0-259.12.beta <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

  # From Dart Team: Get current device information from within the Flutter application.
  device_info: ^2.0.0

  # From Dart Team: A composable, Future-based library for making HTTP requests.
  http: ^0.13.0

  # From Flutter Team: Provides an API for querying information about an application package.
  package_info: ^2.0.0

  # From Flutter Team: Wraps NSUserDefaults (on iOS) and SharedPreferences (on Android).
  shared_preferences: ^2.0.3

  # From Flutter Team: A Flutter plugin for launching a URL in the mobile platform.
  url_launcher: ^6.0.2

  # A dart library for comparing and incrementing version numbers with Semantic Versioning.
  version:  ^2.0.0-nullsafety

  # A dart library for parsing, traversing, querying, transforming and building XML documents.
  xml: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # From Dart Team: Mock library for Dart inspired by Mockito.
  mockito: ^5.0.0
  pedantic: ^1.11.0
 
flutter: